name: CI/CD for Frontend

on:
  push:
    paths:
      - 'frontend/**'
    branches:
      - main

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        run: npm install rollup
        run: npm install @swc/core

      - name: Build React app
        run: npm run build

      - name: Deploy Frontend (nếu cần)
        run: echo "Deploying Frontend..."
